name: Build

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    strategy:
      matrix:
        go: [1.18, 1.19]
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3
      - name: Build the stack
        run: |
          docker-compose up -d

      - name: Run tests
        run: |
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}